### ISSUE TITLE
Issue with MIDI2LR having phantom MIDI command calls.

### ISSUE THREAD

**Issue by renarsvilnis** [rsjaffe/MIDI2LR#469] opened 2020-01-22 12:39 UTC
Hi,
I have an issue where MIDI2LR is triggering events (see video) both when the midi-controller is/isn't plugged in. While recording didn't have any peripheries plugged in the MacBook.
These happen as soon as I start Lightroom.

https://www.youtube.com/watch?v=yiFctXVgaLo&feature=youtu.be

Using MacBook Pro (15-inc, 2016).

Anyone else has had similar issues?

```
----------- LIGHTROOM -----------
Operating system 10.15.2.19C57 (x64)
Version 9.0
Language en
Preferences path /Users/renarsvilnis/Library/Preferences/Adobe/Lightroom
Application data path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom
----------- PLUGIN -----------
Version 3.4.9.1
Path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom/Modules/MIDI2LR.lrplugin
MIDI2LR log path /Users/renarsvilnis/Library/Logs/MIDI2LR
MIDI2LR data path /Users/renarsvilnis/Library/Application Support/MIDI2LR
----------- APP -----------
Application: System language en-LV.
Application: Application version 3.4.9.1.
Application: Application path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom/Modules/MIDI2LR.lrplugin/MIDI2LR.app.
Application: Profile directory /Users/renarsvilnis/Google Drive/Programming/Settings/midi2lr.
Application: Log file directory /Users/renarsvilnis/Library/Logs/MIDI2LR/.
Application: Settings file directory /Users/renarsvilnis/Library/Application Support/MIDI2LR/.
Application: Keyboard type .19131
```

```
**********************************************************

Log started: 15 Jan 2020 3:48:50pm

2020-01-15T15:48:50.067+01:00: MenuTrans.xml archive loaded from /Users/renarsvilnis/Library/Application Support/MIDI2LR/MenuTrans.xml.
2020-01-15T15:48:50.075+01:00: ControlsModel archive in Main loaded from /Users/renarsvilnis/Library/Application Support/MIDI2LR/settings.xml.
2020-01-15T15:48:50.126+01:00: Command not found in CommandTextIndex: Unmapped.
2020-01-15T15:48:50.126+01:00: Command not found in CommandTextIndex: Unmapped.
2020-01-15T15:48:50.126+01:00: Command not found in CommandTextIndex: Unmapped.
2020-01-15T15:48:50.127+01:00: Trying to open input devices.
2020-01-15T15:48:51.918+01:00: Opened input device IAC Driver Bus 1.
2020-01-15T15:48:51.919+01:00: Opened input device IAC Driver IAC Bus 2.
2020-01-15T15:48:51.922+01:00: Opened output device IAC Driver Bus 1.
2020-01-15T15:48:51.923+01:00: Opened output device IAC Driver IAC Bus 2.
2020-01-15T15:48:51.926+01:00: Socket connected in LR_IPC_In.
2020-01-15T15:48:51.928+01:00: Socket connected in LR_IPC_Out.
2020-01-15T15:48:51.928+01:00: Pickup is enabled.
2020-01-15T15:48:51.929+01:00: Application: System language en-LV.
2020-01-15T15:48:51.929+01:00: Application: Application version 3.4.9.1.
2020-01-15T15:48:51.929+01:00: Application: Application path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom/Modules/MIDI2LR.lrplugin/MIDI2LR.app.
2020-01-15T15:48:51.929+01:00: Application: Profile directory /Users/renarsvilnis/Google Drive/Programming/Settings/midi2lr.
2020-01-15T15:48:51.929+01:00: Application: Log file directory /Users/renarsvilnis/Library/Logs/MIDI2LR/.
2020-01-15T15:48:51.929+01:00: Application: Settings file directory /Users/renarsvilnis/Library/Application Support/MIDI2LR/.
2020-01-15T15:48:51.932+01:00: Application: Keyboard type .
2020-01-15T15:48:52.234+01:00: Version available 3.4.9.1, version last checked 3.4.8.0, current version 3.4.9.1.
2020-01-15T15:48:52.288+01:00: Plugin: Operating system 10.15.2.19C57 (x64).
2020-01-15T15:48:52.288+01:00: Plugin: Lightroom Version 9.0.
2020-01-15T15:48:52.290+01:00: Plugin: Lightroom Language en.
2020-01-15T15:48:52.293+01:00: Plugin: Lightroom Preferences path /Users/renarsvilnis/Library/Preferences/Adobe/Lightroom.
2020-01-15T15:48:52.293+01:00: Plugin: Lightroom Application data path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom.
2020-01-15T15:48:52.293+01:00: Plugin: Plugin version 3.4.9.1.
2020-01-15T15:48:52.293+01:00: Plugin: Plugin path /Users/renarsvilnis/Library/Application Support/Adobe/Lightroom/Modules/MIDI2LR.lrplugin.
2020-01-15T15:48:52.293+01:00: Plugin: Plugin log path /Users/renarsvilnis/Library/Logs/MIDI2LR.
2020-01-15T15:48:52.294+01:00: Plugin: Plugin data path /Users/renarsvilnis/Library/Application Support/MIDI2LR.
```

**Comment by antzwire** [comment] 2020-02-05 15:44
i do have same thing last week from a month use... did you find a solution already...?

**Comment by renarsvilnis** [comment] 2020-02-05 15:55
@antzwire No 😞

**Comment by bitDealer** [comment] 2020-07-15 16:31
Have you found a solution yet? I think it started when I installed a new MIDI-Driver (loopMIDI) for some other project

**Comment by rsjaffe** [comment] 2020-09-03 22:04
Duplicate of #483

**Closed by rsjaffe** 2020-09-03 22:04 UTC
Labels: Bug

**Comment by antzwire** [comment] 2020-09-05 02:41
i cant say a total solution.... but i recently making it working when i took off the free capture one the i delete it and reinstall it again....  im not done assigning every inputs i need, but i am planning to keep it simple.... hope it will keep working....

**Comment by renarsvilnis** [comment] 2020-09-05 09:57
You can confirm, had a virtual "serial-2-midi" interface for Arduino. Can't wait for the select midi controller option!
