### ISSUE TITLE
BCF2000 motors stopped working 0.7.0

### ISSUE THREAD

**Issue by LeJimi** [rsjaffe/MIDI2LR#88] opened 2015-12-10 15:53 UTC
Hi there,

I upgraded to 0.7.0 (running Win 10) and do not get response from motorized sliders when moving from one photo to another. I performed this sequence of steps, and get it to work again, then it stopped again...

0. After 0.7.0 installation - motors became non-responsive
1. Upgraded BCF2000 firmware to 1.10
2. Performed BCF2000 reset (Panic Reset was sufficient)
3. Removed 0.7.0 folder (for some reason Remove option is greyed out in Lightroom Plugin Manager, so I had to hard delete the folder)
4. Reinstalled 0.7.0
5. Got motors back again.
6. Setup new profile, saved, worked a bit, then motors stopped again.
7. Reinstalled 0.7.0 the same way as above - can't get the motors to work again...

Btw. When using Rescan MIDI Devices - it causes 0.7.0 to crash.
I notice red LED lights A and B flashing when switching between photos, but no motors action.

Can't use it withouth the motorized sliders and updating their status from one photo to the next is crucial for smooth work.

Anyone with similar issue?

Thanks,
Andrzej

**Comment by krakozavr** [comment] 2015-12-10 16:32
I expected something similar when I did the setup.
Finally, everything is working for me. I even posted my templates here.

Check these steps:

- try to reset the device. The "panic" didn't worked for me, but here is the other way. Turn your device "off", then press and hold the top left button and turn it on. After this, set the USB mode 1 (press Edit and Store together, then set the mode by the first knob, then press Exit)

- check for sliders settings with BC Manager. SYNC option for slider should be set to "motor".

Also, you can try my templates posted here :-)

**Comment by russellhow** [comment] 2015-12-10 19:31
Same problem here.  Motors not working in 0.7.0.  Tried above but no joy so gone back to 0.6.0 for now.

**Comment by krakozavr** [comment] 2015-12-10 19:42
I definitely have had this issues (and even many time, at first I even tough that my device is broken). But finally, after resetting, system template's editing and uploading, I have totally working device with 0.7.0 app, so I can confirm that the app's version don't cause this issue by itself.

I'm not sure because my initial setup was a little bit chaotic, but I think that at least once my sliders issue was disappeared after preset's switching with the hardware buttons at the device.

**Comment by russellhow** [comment] 2015-12-10 19:45
Thanks krakozavr - I'll have another go next week - I have an edit due out tomorrow so I'm sticking with what works for the sake of speed before I have another go at sorting it out :-)  Thanks!

**Comment by LeJimi** [comment] 2015-12-11 12:48
I tried the reset and USB mode 1 (showing as u-1, I assume this is it) - no joy.
Then I tried to find SYNC option as "motor" in BC Manager, but I couldn't find it anywhere in the software...

So my issue is persisting, and I cannot make my motors work again... Gutted.

**Comment by russellhow** [comment] 2015-12-11 12:57
Go back to v0.6.0?  That's what I've done and it's workoing fine.

**Comment by krakozavr** [comment] 2015-12-11 13:04
In BC Manager, go to "view" - "b-controls"
Thee you should see your device. 
Dubble-click on this. You should see your device "inside" - it will be the table with preset's list. Each row represented one preset.
With buttons at the top of the windows, you can choice for each preset a full layout, or controls (sliders, buttons, knobs).
Then doubble-klick to your control element (specific slider), you will see options for this. Each slider have individual settings, it may be different at different layouts.

**Comment by LeJimi** [comment] 2015-12-11 13:13
Hallelujah! Easy does it. 0.6.0 FTW.

Thanks krakozavr, I found these elements and they were set to move. I changed to motor, and was just about to send these global settings to my unit, but for now I'm good with 0.6.0, as I'm kinda afraid new settings might screw things up even more...

I'll wait up for new versions and test them if they work fine, with a fall-back option of 0.6.0

Thanks guys, for now problem solved, but I guess few more people may have the same issue of no motors in 0.7.0... :(

**Comment by krakozavr** [comment] 2015-12-11 13:15
BTW, friends. Just to be sure.
Did you tried this suggestion from the FAQ?

"Motorized faders stop working after upgrading MIDI2LR. Closing the MIDI2LR app then restarting LR should fix this. This is a LR issue"

?

**Comment by LeJimi** [comment] 2015-12-11 13:32
Yup, first thing I saw in the notes. 

I did that roughly a hundred times in the last 2 days. Simple restart did nothing. Once I reverted to 0.6.0 - the issue went away straight away. So it must be my hardware combination clashing with the new 0.7.0... bummer.

**Comment by ajaxandy** [comment] 2015-12-11 16:38
@krakozavr please can you post some screen shots as I can't find the options you mention in B-Control.  It sounds like you are in this screen but I'm not 100% sure?  I'm also having problems with the faders not changing back to the default position when I go to the next photo.

![b-control layout](https://cloud.githubusercontent.com/assets/16177532/11749413/8b38277c-a025-11e5-9993-e4298bc5f215.jpg)

**Comment by krakozavr** [comment] 2015-12-11 17:49
@Ajaxandy, I can't because I'm in travel now. But you are at the right place :-). Now you see the full layout for the preset "0" (you can switch the preset  with arrow next to the red "0" at the top).

Duble-click at the control element you want (4 groups at the top are knobs, then buttons, then "encoders" = sliders) and check the properties. It should be a popup window with some tabs.

Also, I shared ad this forum my template edited for BCF2000. You can use it - just upload it yo the device with BC Manager (I suggest you yo save your current settings before). Probably you will found it useful, at least as the base for further tuning. For me, it working with BCF2000+MIDI2LR 7.0.7 under Windows 10.

**Comment by ajaxandy** [comment] 2015-12-11 18:02
Thank you for the reply @krakozavr! :) I didn't know the Encoders were the sliders so that was extremely helpful.

Once I double click I get the properties but I'm not sure what to change... is it in one of these tabs?

![b-control layout - properites of encoders 1](https://cloud.githubusercontent.com/assets/16177532/11751429/61e54de4-a031-11e5-84a5-71d64c5d1c33.jpg)

![b-control layout - properites of encoders 2](https://cloud.githubusercontent.com/assets/16177532/11751430/61f9b874-a031-11e5-9c73-f06c7db287da.jpg)

**Comment by krakozavr** [comment] 2015-12-11 18:51
@ajaxandy - oops, sorry, I was messed - encoders it's knobs, definitely. And these screenshoots are for encoders's settings. But I understand now why I was messed. Look, the main "layout" screenshot is for BCR2000, not BCF. This is a different devices. BCR haven't sliders at all, just knobs (encoders); but the main layout window looks similar, especially at the small screen of my cellphone :) I was confused at the first glance because I thought that "encoders" should be knobs; bet because I have no possibility to refer the app and they are located at the same places as sliders, I gave You the wrong advice, sorry about this.

So, check your device connection. And you have to choice the proper device in BC Manager. When you will have the proper connected BCF2000 you will see sliders (sorry again for mess), and you will see the SYNC parameter at the GENERAL tab

**Comment by ajaxandy** [comment] 2015-12-16 09:51
Thank you @krakozavr, i've changed it to BCF (well spotted!) and all the sliders are set to 'motor' already... am I right in thinking this means they should be automatically resetting to the default position when I change photo or is there something else I need to do?

**Comment by ajaxandy** [comment] 2015-12-16 10:15
@krakozavr it's working now woohoo!!!  Not sure what happened as I set up some presets and assigned them to the Midi controller and suddenly the Faders started doing their thing... might have just been a delay in LR picking them up?  Anyway huge thanks for all your help... really appreciate it! :)

**Closed** 2015-12-17 15:03 UTC

**Comment by LeJimi** [comment] 2015-12-21 13:23
Sorry guys, the issue is still here on my machine.

First everything fcuked up when i uploaded updated templates to BCF2000. Midi stopped talking with MIDI2LR completely, I'm not talking lack of motors feedback, but not even picking up moves to setup functions in the first place. Total no response.

Then I uploaded @krakozavr templates to bring it back to life. Motors started to talk to MIDI2LR, I did setup my functions, now motors also respond to changed photos - everything works perfectly.

Then i update to 0.7.0 and back to the same issue - talking with MIDI2LR, but no motor response between photos.

Go back to 0.6.0 - everything works fine again.

On my machine - 0.7.0 gives troubles. Not sure where the issue is.

**Comment by krakozavr** [comment] 2015-12-21 17:11
I got the same issue when I updated to 0.8.0
What you have to try to do:
- close LR
- update MIDI2LR
- start LR
The plug-in will started,  then restart LR and plugin again (probably it's
unnecessary step but do it)
- turn BFC2000 off and on.  Sliders should moved to the default pisition
- go to the MIDI2LR settings and rescan the device.

Now,  sliders should work.

On Mon, Dec 21, 2015, 8:23 AM LeJimi <notifications@github.com> wrote:

> Sorry guys, the issue is still here on my machine.
>
> First everything fcuked up when i uploaded updated templates to BCF2000.
> Midi stopped talking with MIDI2LR completely, I'm not talking lack of
> motors feedback, but not even picking up moves to setup functions in the
> first place. Total no response.
>
> Then I uploaded @krakozavr <https://github.com/krakozavr> templates to
> bring it back to life. Motors started to talk to MIDI2LR, I did setup my
> functions, now motors also respond to changed photos - everything works
> perfectly.
>
> Then i update to 0.7.0 and back to the same issue - talking with MIDI2LR,
> but no motor response between photos.
>
> Go back to 0.6.0 - everything works fine again.
>
> On my machine - 0.7.0 gives troubles. Not sure where the issue is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsjaffe/MIDI2LR/issues/88#issuecomment-166304828>.
>
-- 

Best regards,
Alex Potemkin,
AlexArtPhoto.

krakozavr@gmail.com

USA phone: +1 610-714-14-94

My fresh and selected photos: http://yourphoto.nyc
My studio info and customers's reviews: http://yourphoto.biz
My portfolio on iStockPhoto: http://istock.yourphoto.biz
My portfolio on GettyImages: http://getty.yourphoto.biz
My printed posters at FineArtAmerica:
http://alex-potemkin.artistwebsites.com

**Comment by LeJimi** [comment] 2015-12-22 03:21
I tried that but no cigar...

I feel there is a bug somewhere, and restarting might help some people. It doesn't in my case, so I need to stay on 0.6.0 for now...

@rsjaffe any chance to see what's the root cause? I'd love to jump onto 0.8.1... Thanks man!

**Comment by krakozavr** [comment] 2015-12-22 04:10
did you tried not just restart but RESCAN the device? It helped me every time when my device's sliders stopped working (and I performed MANY upgrades past days :) )

**Comment by LeJimi** [comment] 2015-12-22 04:37
In my previous troubles 0.6.0 just crashed upon clicking Rescan device.
Now it works, but motors are still unresponsive. I can slide to make
changes to each photo, they just do not get updated between photos.

On Tue, Dec 22, 2015 at 12:10 PM, Alex Potemkin <notifications@github.com>
wrote:

> did you tried not just restart but RESCAN the device? It helped me every
> time when my device's sliders stopped working (and I performed MANY
> upgrades past days :) )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsjaffe/MIDI2LR/issues/88#issuecomment-166500960>.
>



-- 
Regards,

Andrzej Wisniewski

**Comment by krakozavr** [comment] 2015-12-22 21:11
@LeJimi and other, take a look here please? https://github.com/rsjaffe/MIDI2LR/issues/106

**Comment by LeJimi** [comment] 2015-12-24 03:45
Thanks man. I only shoot RAW, and never import JPEGs to Lightroom, so we
can eliminate that cause...

So far working on 0.6.0, as it gives me most of what i need and keep the
workflow going.


On Wed, Dec 23, 2015 at 5:11 AM, Alex Potemkin <notifications@github.com>
wrote:

> @LeJimi <https://github.com/LeJimi> and other, take a look here please?
> #106 <https://github.com/rsjaffe/MIDI2LR/issues/106>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsjaffe/MIDI2LR/issues/88#issuecomment-166730370>.
>



-- 
Regards,

Andrzej Wisniewski
