### ISSUE TITLE
Temperature value 

### ISSUE THREAD

**Issue by thorodt** [rsjaffe/MIDI2LR#239] opened 2016-04-08 17:51 UTC
### Expected behavior
Temperature value is working only for raw files, not for JPG
the TINT value is working for both formats

### Actual behavior
the Temperature value for jpg is not working

### Steps to reproduce the behavior
try to change Temperature in Lightroom 6 for a JPG

### System information

* Operating system (Windows or OS X) and version:  OS 10,9,2
* MIDI2LR version: 0.9.9
* Lightroom version: 6,0
* Lightroom language: italian
* Keyboard language: italian
* MIDI controller: xtouch mini behringer
* Plugin installation directory: /user/desktop/MIDI2LR/
* Profiles save directory: /LIGHTROOM/

**Comment by rsjaffe** [comment] 2016-04-09 06:40
Could you open a jpg in Develop module, then look at the plugin options menu: other options, and check the temperature limits?

**Comment by thorodt** [comment] 2016-04-09 10:15
for JPG the temperature range is from -100 to + 100
for raw  2000 - 50000

**Comment by rsjaffe** [comment] 2016-04-09 18:22
Odd. I can't reproduce the error. I've flagged this to see if anyone else is having the same issue.

**Comment by alexsheppard11** [comment] 2016-04-10 17:14
I can reproduce with 0.9.10.1 and LR 6.5.

**Comment by Slelmo** [comment] 2016-05-18 17:16
I can confirm this with TIFs. One of those that PS (CS6) sends back to LR. 
Haven't touched a JPG in a while so can't tell.

Lightroom version: 6.5 [ 1067055 ]
MIDI2LR version 1.0.0.1

**Comment by rsjaffe** [comment] 2016-05-19 02:49
See #255. Will be fixed (I hope) in next release.

**Closed by rsjaffe** 2016-05-19 02:49 UTC
Labels: Anyone else experiencing this issue?, Troubleshooting

**Comment by thorodt** [comment] 2016-05-19 07:28
thanks a lot :)
