### ISSUE TITLE
Internal error when trying to use options

### ISSUE THREAD

**Issue by MrGBCF2000** [rsjaffe/MIDI2LR#166] opened 2016-02-02 19:23 UTC
Hi Rory,

I got the correspondance window below when trying to start options with 0.9.5.
In case of 0.9.1 version options works well
LRCC WIN7 BCF2000

![ie](https://cloud.githubusercontent.com/assets/16202708/12761216/4ee29c1e-c9ea-11e5-8435-e4eea35eab27.png)

What is this referring to?

Thanks a lot

**Comment by rsjaffe** [comment] 2016-02-02 23:18
Please re-download the new version and try again. There was a problem with one of the files when I first posted it.

**Comment by rsjaffe** [comment] 2016-02-03 06:32
I can't replicate the bug, but a new version is available for download that addresses what seems to be the cause. The app will still show 0.9.5 but the plugin will show 0.9.5.2. Because of a problem with the app, I can't use the build numbers in general releases.

Please try the new version and respond with your results. If you continue to have problems, we'll have to dig deeper.

**Comment by krakozavr** [comment] 2016-02-03 19:18
everything OK with settings copy-past and profiles switching with this new release.

**Comment by krakozavr** [comment] 2016-02-03 19:32
ooops. Not ALL.
The assigned lens profile doesn't copying.
The situation is:
I have the Sigma lens attached to the Sony camera via the adapter. So, the info about the lens is not properly write in the metadata.
When editing, I pick the lens in the "lens profile" manually, but when I do copy - past setting, the checkbox status "enable profile corrections" is transferred but the assigned info about the lens is not.

I do some additional research, and I found that, if I save the manually-assigned profile, copy-past works correct (the profile is "default"). And unsaved changes of the profile can't be copied. It may be a problem if you are using different manual-focus lenses, as I do. In the case with canon/sigma lenses, part of info needed for the lens identification still available. But fot old-style manual-focus lenses (M42) it isn't, all those lenses looks totally same for the LightRoom, so saving of the profile may not be very helpful. Not a critical issue, but still be issue :)

**Comment by MrGBCF2000** [comment] 2016-02-03 20:17
Thanks for prompt update, however I still receive the same window with 0.9.5.2  
Latest release where options working is 0.9.4 for me.
It seems a specific issue with my setup. :S 

![ie2](https://cloud.githubusercontent.com/assets/16202708/12795660/4c5c369a-cabb-11e5-85b1-7dcdd2c0a9fb.png)

**Comment by rsjaffe** [comment] 2016-02-03 22:11
Weird. Could you go back to 0.9.4, open the options menu, and press "OK"? I'm wondering if their's something corrupted in your saved preferences. Doing a new save should fix it. 

If that doesn't do it, there's a hidden way to completely scrub the old preferences and save the new ones.

In 0.9.4, open up Options.lua in notepad, and add the word *true* (all lower case) to the call to *Preferences.Save* that is near the bottom of the file.:

```lua
      if result == 'ok' then
        Preferences.Save()
```
to
```lua
      if result == 'ok' then
        Preferences.Save(true)
```

Then restart Lightroom, open the options dialog, and press OK. That will scrub the old stuff. You can remove the *true* after that if you wish, but the only affect it has is removing preferences from legacy versions of MIDI2LR, which you're not using if you're in the 0.9.x series.

**Comment by StevenKersting** [comment] 2016-02-06 04:14
I have found an issue where accessing the options dialogue from any panel other than the develop panel generates an error... are you in the develop module?

**Closed** 2016-02-06 04:29 UTC
Labels: bug, fixed
