### ISSUE TITLE
Crop by considering the locked ratio value

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#317] opened 2016-11-15 14:43 UTC
See: https://mail.google.com/mail/u/0/#label/%23midi2lr/158429faf0bf83c6

Currently, cropping does not consider the ratio lock, so it's free.

Users want to be able to lock their ratio (original, 4/3, 16/9, etc), and crop.

This would require only mapping 2 things: Crop Left and Crop Right. Or Bottom and Up.

The idea would be that when a slider is moved, we detect if there's a ratio locked, and we compute the other values thanks to the image ratio.

This requires:

- being able to access the image or crom dimensions to compute a ratio
- being able to access the state of "ratio lock" (or, if we cannot, provides 2 new commands in the menu: Left Crop Locked and Right Crop Locked). These menu items would then mean that they consider the aspectt ratio of the image

**Comment by rsjaffe** [comment] 2018-01-06 02:54
Duplicate of #413

**Closed by rsjaffe** 2018-01-06 02:54 UTC
Labels: Enhancement, ready
