### ISSUE TITLE
Second value during initial adjustment

### ISSUE THREAD

**Issue by PitToad** [rsjaffe/MIDI2LR#682] opened 2022-08-13 16:06 UTC
### Discussed in https://github.com/rsjaffe/MIDI2LR/discussions/679

<div type='discussions-op-text'>

<sup>Originally posted by **PitToad** August 12, 2022</sup>
LR 11.4.1, MidiLR 5.4.0.0
Sony RAW Files

When editing a new RAW/ARW file, the adjustments don't alway start at zero, and I have to adjust up or down to zero for Lightroom to then reflect adjustments.

Using Midifighter Twister or Arturia Beatstep have same effect - Is there something I've not ticked?

Adjustment doesn't always start at zero, even on newly imported, unedited pics - the first value is the Clarity value last made on a previous pic and the '0' is the Clairty adjustment for this pic
![cla2](https://user-images.githubusercontent.com/111119318/184327106-f2e33cf4-3c9e-44df-899a-9b4f0b218b25.jpg)

Adjusting Carity + has no effect on Clarity slider or value
![cla3](https://user-images.githubusercontent.com/111119318/184327163-db23ef3f-834b-4905-b712-6553da11d4cd.jpg)

Once encoder goes past zero (Now into Clarity negative values, so past zero from positive values) , adjustments are visible on Lightroom
![cla5](https://user-images.githubusercontent.com/111119318/184327192-55984926-e0e4-4b36-bab6-fe5c9acd47fb.jpg)

</div>

**Comment by lovelacecreativeco** [comment] 2022-12-09 22:12
Have you tried 'Enable Pickup Mode' ?

**Comment by darthdurden** [comment] 2023-02-04 20:28
I've seen similar behavior. It always seems to occur when I switch layers on my X-Touch Mini. The software seems to not be quite syncing the current lightroom values with the current midi values. For instance if I double-press the A button to switch to the layer, all of the lights go to 0 instead of the selected values. 

I've tried turning off pickup mode and it works better in some respects, but it also works a lot worse in others so its not viable.

I can pretty reliably reproduce this by switching through layers, though I can't determine what the exact triggering pattern is.

I've also noticed that if I switch to layer B, the lights on my dials don't correspend with the selected dials at all (they are just off) unless I start turning them.

**Comment by wunditta** [comment] 2023-09-23 01:41
This is definitely the pickup mode, when enabled this is it's intended behavior. When a slider value and the value in Lr do not match, and for some reason the value on the MIDI device cannot be set to the current Lr value, the plugin waits (movement has no effect) until the slider value (first value shown) reaches the Lr value (second value shown).

You can disable pickup mode in the application settings, then the Lr value is always set to the MIDI control. But I cannot say which is better.

I do have the X-Touch Compact and cannot reproduce this issue. Neither with the motorized sliders, nor with the dial knobs, nor by switching layers. Whatever I do, the Compact gets updated with the correct values. When I switch to layer B the LEDs on the dial change of course, going back to A sets them to the value before and I can continue changing the parameter normally.

Is this still an issue, by the way? Maybe it is something with the Mini and there is a new firmware?

**Comment by rsjaffe** [comment] 2024-03-02 01:42
Fixed in https://github.com/rsjaffe/MIDI2LR/commit/4605af1b46ef52cae9ecfabf0a35fdca7a5718d5

**Closed by rsjaffe** 2024-03-02 01:42 UTC
