### ISSUE TITLE
Status and activity captions have some unneeded notes

### ISSUE THREAD

**Issue by leonlazic** [rsjaffe/MIDI2LR#447] opened 2019-05-25 19:03 UTC
**Describe the bug**
The status and activity box has some notes that shouldnt realy be visible to the end user. 
It doesn't happen with all settings but some I tested are: highlights, shadows, whites, (probably more). Instead of shoving for example "Highlights" and the value next to it, it shows "Highlights (Highlights Recovery in PV2003 and PV2010)" and then the value.

**To Reproduce**
1. Activate the "Show status and activity" option in "Set MIDI2LR options" window under "Other..." tab

**Expected behavior**
I think I should be like in previous versions where it was nice and simple just "Highlights" with the value next to it.

**Screenshots**
<img width="854" alt="Screenshot 2019-05-25 at 20 54 10" src="https://user-images.githubusercontent.com/26551422/58373564-5f90e580-7f30-11e9-9b52-42fe19fbdfa6.png">

**System:**
 - OS: MacOS Mojave 10.14.4
 - Lightroom version 8.3
 - MIDI2LR version 3.1.0.4
 - Controller X-Touch Mini

Best regards Leon

**Comment by rsjaffe** [comment] 2019-06-03 20:40
It's a feature, not a bug :-) . The meaning of the control depends upon the process version of the photo, so the text is necessary. The only way to change the behavior would be to change the label according to the process version of the current photo, which would require changing the program's database structure to add PV-specific label translations and testing for process version in the plugin's message loop, which could impede responsiveness. Since the current label is correct (though wordy), I'm not planning to do anything about it.

**Comment by rsjaffe** [comment] 2019-06-05 17:08
I found a way to avoid testing for process version, and updating it without any extra delay. I'm going to try to implement your request.

**Comment by leonlazic** [comment] 2019-06-05 17:10
Awesome. I think it would look much more polished if there was just the word Highlights like there is when you move the slider.

**Comment by rsjaffe** [comment] 2019-06-05 18:48
The fix is in the latest develop commit. Turns out that I _did_  have to check for process version, but did it in the bezel code instead of the message loop, so the cost is not as much, though I suspect it does marginally slow down the display.  You can download the latest ClientUtilities.lua and Database.lua files and replace in your copy of MIDI2LR.lrplugin if you want to test it out.

**Closed by rsjaffe** 2019-06-05 18:48 UTC
Labels: Bug

**Comment by rsjaffe** [comment] 2019-06-05 19:54
I just pushed another commit because the original one broke the Limits code, which also depends upon label translations. Fixed, now.
