### ISSUE TITLE
[string "Profiles.lua"]:75: attempt to perform arithmetic on a string value

### ISSUE THREAD

**Issue by WaellerKlaus** [rsjaffe/MIDI2LR#137] opened 2016-01-12 17:57 UTC
The above error message appeared when switching automatically from one profile to the profile   assigned to the basic develop panel profile because of a respective slider was used. At the same time the crop-tool was active. MIDI2LR (release 0.9.2) on Mac OS X 10.10.5 (14F1021) using Lightroom 6.3 [ 1052427 ].

**Comment by rsjaffe** [comment] 2016-01-12 18:02
What were you doing to trigger that error?

**Comment by WaellerKlaus** [comment] 2016-01-12 18:05
just added the description.

**Comment by rsjaffe** [comment] 2016-01-12 18:06
argh. OK, could you try the following?

in Profiles.lua, replace the resync function?

```lua
local function resync()
  if LrApplicationView.getCurrentModuleName() == 'develop' then
    -- refresh MIDI controller since mapping has changed
    for _,param in ipairs(Parameters.Order) do
      local min,max = Limits.GetMinMax(param)
      local midivalue = (LrDevelopController.getValue(param)-min)/(max-min) * MIDI2LR.CONTROL_MAX
      MIDI2LR.SERVER:send(string.format('%s %g\n', param, midivalue))
    end
    resyncDeferred = false
  else 
    resyncDeferred = true
  end
end
```

with
```lua
local function resync()
  if LrApplicationView.getCurrentModuleName() == 'develop' then
    -- refresh MIDI controller since mapping has changed
    for _,param in ipairs(Parameters.Order) do
      local min,max = Limits.GetMinMax(param)
      local lrvalue = LrDevelopController.getValue(param)
      if type(min) == 'number' and type(max) == 'number and type(lrvalue) == 'number' then
        local midivalue = (lrvalue-min)/(max-min) * MIDI2LR.CONTROL_MAX
        MIDI2LR.SERVER:send(string.format('%s %g\n', param, midivalue))
      end
    end
    resyncDeferred = false
  else 
    resyncDeferred = true
  end
end
```

**Comment by WaellerKlaus** [comment] 2016-01-12 18:20
no luck. After editing the file I cannot start MIDI2LR from within LR anymore. It immediately get's "deactivated" due to a problem. I've used Textwrangler as an editor, because I was quite sure it would not change the character encoding. Any recommendation?

**Comment by krakozavr** [comment] 2016-01-12 18:22
Same here. Windows 10.
Changes was made by EditPlus, I used it to make some changes in LUA for iGO, so it should be OK.

after changes in LUA, plugin can't be loaded, diagnostic message from LightRoom's plugin manager 
[diad902.txt](https://github.com/rsjaffe/MIDI2LR/files/87761/diad902.txt)
is attached.

**Comment by WaellerKlaus** [comment] 2016-01-12 18:24
got it!
there was a closing quote missing in the newly added if statement.


local function resync()
  if LrApplicationView.getCurrentModuleName() == 'develop' then
    -- refresh MIDI controller since mapping has changed
    for _,param in ipairs(Parameters.Order) do
      local min,max = Limits.GetMinMax(param)
      local lrvalue = LrDevelopController.getValue(param)
      if type(min) == 'number' and type(max) == 'number' and type(lrvalue) == 'number' then
        local midivalue = (lrvalue-min)/(max-min) * MIDI2LR.CONTROL_MAX
        MIDI2LR.SERVER:send(string.format('%s %g\n', param, midivalue))
      end
    end
    resyncDeferred = false
  else 
    resyncDeferred = true
  end
end

**Comment by WaellerKlaus** [comment] 2016-01-12 18:29
Problem solved for me! Many thanks for the quick action.
I've confirmed profile switching in that same situation, where the error occured.
[Profiles_copy.lua.txt](https://github.com/rsjaffe/MIDI2LR/files/87784/Profiles_copy.lua.txt)

**Comment by krakozavr** [comment] 2016-01-12 18:49
@WaellerKlaus thank you, I can confirm, it was just a typo. All done :)

**Comment by rsjaffe** [comment] 2016-01-12 20:38
OK, I just updated the release to 0.9.2a. Could you do me a favor and download that and see if it is ok?

**Comment by WaellerKlaus** [comment] 2016-01-12 22:28
Thank you for the quick fix. Release to 0.9.2a is o.k. Tested on a Mac. Probably beeing able to test Win7 tomorrow.

**Comment by WaellerKlaus** [comment] 2016-01-12 23:25
It appears, that the Info.lua file still has "VERSION = { major=0, minor=9, revision=1}". Just stumbled over it when installing on the Windows machine.
Profile changes on the Windows machine are working as expected mostly using 0.9.2a, however I managed to crash MIDI2RL one time. Tried to reproduce in order to describe the handling procedure, but it didn't yet crash again. Testing profile on Windows is easier than on a Mac as there is a nice notification about when an which profile gets loaded. My Mac is really silent about this.

**Comment by rsjaffe** [comment] 2016-01-13 00:06
The version number was messed up because it won't take a mixture of numbers and letters. It will be fixed tonight. 

On the mac, the app should still show which profile is loaded near the bottom of the window. It's listed just above the "Remove Selected Row" button. See image below.
<img src="https://camo.githubusercontent.com/b965d0c776974d8a03a4b359350aa305708a0ea6/687474703a2f2f72736a616666652e6769746875622e696f2f4d494449324c522f696d616765732f617070763038322e706e67" />

**Comment by rsjaffe** [comment] 2016-01-13 03:20
release 0.9.3 out

**Closed by rsjaffe** 2016-01-13 03:20 UTC
