### ISSUE TITLE
Controller LED states

### ISSUE THREAD

**Issue by leonlazic** [rsjaffe/MIDI2LR#449] opened 2019-05-25 20:49 UTC
Some of the MIDI contorllers like Behringe X-touch mini have led buttons. It would be awesome to control the state of them. So when something is checked or turned on the button LED stays on. Just an idea that would be really cool. :)

Kind regards Leon

**Comment by rsjaffe** [comment] 2019-06-03 20:35
That's been suggested—it looks pretty complicated to support multiple types of controllers. I may get to it eventually or someone else could try to contribute the needed changes.

Duplicate of #359

**Closed by rsjaffe** 2019-06-03 20:35 UTC
Labels: Enhancement
