### ISSUE TITLE
Feature request and bugs (Behringer X-Touch Mini)

### ISSUE THREAD

**Issue by LUXIIUS** [rsjaffe/MIDI2LR#26] opened 2015-10-15 16:24 UTC
Hi there,

So, after seeing [Pusher Labs](http://www.pusherlabs.com/) "Minimal" based on the Behringer X-Touch Mini, I decided to get one myself. As I'm on PC and the Pusher Labs PFixer software is only for Mac, MIDI2LR comes in handy.
I wanted to emulate the same functionality that PFixer has, but I've met some shortcomings in MIDI2LR. In my testing and setup of my Behringer X-Touch Mini, here is a list of features that I found missing and a few bugs when using that MIDI controller.

**Feature requests**
- Toggle/select specific profiles (i.e. layers)
- Multiple buttons with same function (Handy for things like forward/back buttons on layered MIDI controllers as the X-TM)
- More functions (paste previous, esc, enter, wb, awb, ae, copy, paste, sync, before/after, select left, select right, compare, toggle info)
- Toggle button light when entering mode (Such as crop tool)
- Specific profiles for tools (Handy to be able to control crop tools when in crop mode)
- Reset options on all/most settings (H/S/L, Vignette, WB, Tint, saturation, vibrance, curves)
- Adjust back to 0 (always a little off +/-)
- Start minimized

**Bugs**
- Software "resets" to 63 but lights on knobs center at 64 on the X-TM
- Clicking the active layer button on X-Touch Mini makes the LEDs reset.

**Comment by rsjaffe** [comment] 2015-10-15 17:18
Thanks--

Already implemented in latest code changes, coming out in 0.4.2 release:
* Reset options on all/most settings (H/S/L, Vignette, WB, Tint, saturation, vibrance, curves)

Expected for version 0.5.0 (expected to be next release after 0.4.2):
* Adjust back to 0
* rounding issue (63 vs 64)--might be fixed with 0.5.0, would like to hear from you after that release to see if it's fixed

Toggle button light: this is complicated, as it would require MIDI SysEx messages that would be different for each model of MIDI controller. If you have suggestions on how to do this, I'd be interested to hear

Start minimized: this could be added as future enhancement, probably coupled with a setting to allow this to be controlled by the user, as some would want it opened normally.

Multiple buttons with same function: this feature was *removed* from MIDI2LR as it was causing problems. Could be added back in future if a solution were found for the MIDI controller to program communication problems caused by multiple mapping.

For "Toggle/select specific profiles (i.e. layers)", "Clicking the active layer button on X-Touch Mini makes the LEDs reset." please describe in more detail.

For "More functions", some of those will depend upon finding a cross-platform key press sending solution.

If you have any suggestions for coding for these, please send them my way.

**Comment by LUXIIUS** [comment] 2015-10-15 17:40
Thanks for the quick reply!

Looking forward to the next updates.

In regards to the toggle light, or controlling lights on the different MIDI controllers in general, I'm thinking separate config files for each controller. People can provide new configs for previously unsupported controllers.

So, in regards to my layer request/bug. The X-TM has two layers built in (A/B) and swapping layers updates the LED status on the knobs and buttons and configures a different MIDI signal for the keys, so the controller effectively doubles the number of keys/knobs. If you could assign a key to load a different profile, one could emulate this feature. I'm limited by only having 8 knobs, but I have 2 layers on my controller and if I could press a button to load a specific profile, I could go into a "Hue + Saturation" mode where my knobs on layer A control hue and layer B controls saturation. I could expand with BW mode and such, for much more functionality. Basicly, this is just how Pfixer works. You can see the layout of the controller with that software [here](http://www.pusherlabs.com/media/slideshow/minimal-3.jpg). Let me know if you're having trouble deciphering any on the functions.

On to the layer bug. When I turn on the controller all LEDs are set to light up LED 1 of 13. Starting LR the LEDs updates as they should (well, there is still the rounding issue) and everything is dandy. I can even swap between layer A/B and the LEDs updates just fine for the most part. But if press the layer button on the controller on that layer that is currently active, the controller resets back to 0, which in turn also resets the LED. The change isn't registered in LR however, not before I adjust a knob (I have pick-up mode disabled for now).
There are also times when not every knob is updated when swapping layers, but I haven't found the specific pattern to reproduce this yet.
Ultimately it sounds to me like a communication issue, where the controller resets and the software doesn't push the current value to the controller.

I have yet to dive deep into MIDI2LR, but I'm here for you if you have any further questions regarding this controller.

**Comment by rsjaffe** [comment] 2015-10-22 02:36
See #31

**Closed by rsjaffe** 2015-10-22 02:36 UTC
Labels: bug, enhancement, MIDI message handling, New LR controls

**Comment by ilquare** [comment] 2017-09-07 12:06
Hi LUXIIUS,
I also have this problem:
**But if press the layer button on the controller on that layer that is currently active, the controller resets back to 0, which in turn also resets the LED. The change isn't registered in LR however, not before I adjust a knob (I have pick-up mode disabled for now).**

You have write **I have pick-up mode disabled for now**...How did you do? (through MIDI2LR or other)?
