### ISSUE TITLE
MIDI2LR doesn't update MIDI controller in certain controller and profile configurations

### ISSUE THREAD

**Issue by boomerek** [rsjaffe/MIDI2LR#207] opened 2016-03-01 09:01 UTC
Hi 

Thanks for MIDI2LR as this plugin works flawlessly unfortunately only with RAW files. 
Plugin works and send data back to MIDI controller on the current position in LR, but ONLY with RAW files and doesn't do that when editing  PSD or TIFF files. 
On top of that Temperature slider doesn't move at all with PSD and TIFFS.

**Comment by rsjaffe** [comment] 2016-03-01 15:20
I suggest you check your configuration. Others (including myself) don't have this problem. I did find a PNG that Lightroom refused to allow white balance changes to, but that was in Lightroom itself and not the plugin.

**Comment by boomerek** [comment] 2016-03-01 15:45
Configuration you say.. What do you think can be a reason if the plugin send data back to MIDI controller on the current position in LR when working on RAWs but doesn't sync when editing PSD or TIFF files (it moves them but and every slider has to be "picked up" when changing from one photo to another) 
Midi controller doesn't know which files are which so there must be something in communication between LR and plugin. 

Regarding temp slider I know that temperature is addressed differently in RAW from 2000K to 50000K while in PSD or TIFF it's relative scale from -100 to 100 so it may the reason why it's the only slider that this plugin can't move at all.

Are you sure PSD and TIFF files works exactly the same as RAW in your setup?

**Comment by rsjaffe** [comment] 2016-03-02 00:33
I suggested configuration for two reasons. One, even though you thought a feature was missing, it turned out that misconfiguration was the cause of your first problem. Two, other people are not seeing the issue even though others are also using mixed types of files. You may have uncovered a new problem, but checking the configuration first is important, as many different people are using this program with many different devices and setups. There is a complex interaction between LR, the plugin, the app, the MIDI driver and the MIDI device.

Also, I can't replicate your issue. Everything works fine when I access different types of files. If you describe exactly what you did and what went wrong, that might help me replicate it.

PSD and TIFF files have different ranges for the settings, and that is handled by the plugin, as every translation between LR and MIDI first gets the range from LR for that control at that point in time. 

[This section of the wiki has more about the range differences](https://github.com/rsjaffe/MIDI2LR/wiki/Plugin-Options-Dialog#limits).

**Comment by rsjaffe** [comment] 2016-03-02 01:46
I'm suggesting configuration for several reasons, one, that was the cause of the first bug that you encountered, so I'm wondering what else is going on in your configuration. This whole process is complicated as we are dealing with various MIDI controllers and software, various MIDI drivers, the MIDI2LR app, the MIDI2LR plugin, the LR application, and various user settings (e.g., keyboard language, system language, etc.) Two, because others haven't encountered this issue. I tried to recreate it myself, and was always able to adjust the temperature.

MIDI2LR is ignorant of the file type. It processes each MIDI command according to the range for that adjustment for the current photo, whatever LR tells it it is. It gets the min/max each time a control is moved according to the following code:

```lua
local function GetMinMax(param)
  local rangemin, rangemax = LrDevelopController.getRange(param)
  if Parameters[param] then
    return unpack(ProgramPreferences.Limits[param][rangemax])
  else
    return rangemin,rangemax
  end
end
```

It gets the range for the current photo. It then checks to see if there are limits to that parameter, in which case it gets the limits set for that parameter for that adjustment range (as different photos have different adjustment ranges depending upon bit depth, file type, etc.)

**Comment by boomerek** [comment] 2016-03-02 11:57
Just to clarify the first bug I encountered it's actually the same bug we are discussing here as wasn't because of MIDI controller misconfiguration. The reason it started to work was at that time I tested it with LR folder filled with RAW files while previously I was trying to make it work in folder with TIFF and PSD files only. It turned out it had nothing to do with that change I did in Automap4.
Anyway it seems it's something with my Lightroom then as MIDI controller ha nothing to do with files types and communication between plugin and controller goes smoothly (RAW editing works flawlessly in full sync)

Thanks for trying to help though.
Cheers

**Comment by rsjaffe** [comment] 2016-03-02 17:56
Could you tell me exactly what steps I could take to replicate the problem? If I can replicate it, I can fix it.

**Comment by boomerek** [comment] 2016-03-02 18:11
Basically when I'm working on any RAW files LR sliders works like it this video:
https://youtu.be/M68543e80D4?t=4m1s
so sliders are in full sync with midi controller so even when I slide sliders with mouse on screen it's reflected on the controller too. 
When I'm on any TIFF or PSD that doesn't happened. It's like in one way communication so while I can "pick up" and move sliders with MIDI controller any changes made in lightroom by mouse or what's worse, simply switching from one PSD/TIFF to another does not update knob position on MIDI controller which leads to constant "picking" each and every slider every time you move to next photo.

**Comment by StevenKersting** [comment] 2016-03-03 16:27
I encountered a syncing issue (editing raw files). A restart of LR/M2LR resolved it.

**Comment by rsjaffe** [comment] 2016-03-03 16:55
@StevenKersting -- interesting:: so when you change pictures, controls change accordingly, except for JPG. You've tested Raw (what format), TIFF, PSD, all of which work well.

@boomerek  -- What platform are you on? Mac or PC? You are seeing issues with TIFF and PSD, but not Raw (which format)? Do you see issues with JPG as well?

I am testing on my PC.

For the following files, got correct feedback to the controller when changing pictures:
TIF to TIF, DNG to TIF, TIF to DNG
PSD to PSD, PSD to DNG, DNG to PSD
PNG to PNG, PNG to DNG, DNG to PNG
JPG to JPG, JPG to DNG, DNG to JPG
Checked both motorized sliders and LEDs on knobs: both updated.

My setup: Windows 10, Lightroom CC 2015.4, MIDI2LR 0.9.9, Behringer BCF2000.

**Comment by StevenKersting** [comment] 2016-03-03 17:28
I'm using Nikon so NEF files. 
On further investigation it seems that only the basic panel tone adjustments do not backtalk. Temp/tint, clarity, sat/vib, and detail panel adjustments all do (all of the other ones I checked).

**Comment by rsjaffe** [comment] 2016-03-03 18:08
I hope it's not a LR bug as well. Last LR bug I tried fixing (panel didn't open up when Contrast changed), the fix created more problems than the original problem did.

Currently, almost all the updates are initiated by LR--MIDI2LR has a "listener" that LR notifies when settings have changed, such as when changing photos or when moving a slider on LR itself, rather than in the MIDI2LR app. The only time I force an update is when the app loads a different profile--I refresh all controls then, as some control definitions will have changed and thus be out of sync.

If MIDI2LR isn't getting change notifications when it should, I can try forcing things (e.g., check picture ID in the main program loop, and force a change when the picture ID changes). But I'd rather not.

**Comment by rsjaffe** [comment] 2016-03-03 18:15
Also, could you test the following?

In the edit module, open a file for which you're having problems-- @StevenKersting, for you, it would be jpeg. Confirm you're still having the problem when switching from one file of that type to the next. Then, move a slider on the screen corresponding to one of the controls on your MIDI controller that don't get updated. Does that controller update to correspond to what you did on screen?

**Comment by StevenKersting** [comment] 2016-03-03 18:19
Tested... controller updates do not occur when switching images or when moving the slider in LR. Only for the basic panel tone adjustments and jpegs for me.

**Comment by StevenKersting** [comment] 2016-03-03 18:31
Maybe I was mistaken or something changed... but I now have the same behavior with all file types (basic panel tone adjustments only)

**Comment by StevenKersting** [comment] 2016-03-03 18:37
It is a controller configuration issue... I'll try to sort the specific issue.

**Comment by boomerek** [comment] 2016-03-03 18:49
Ok, I just checked that and editing all RAW files I have NEF, CR2, ORF is in full sync with midi controller so when I move sliders with mouse on screen it's reflected on the controller too. 
With JPEG, DNG, PSD, TIFF that doesn't work.

My setup: Windows 10, Lightroom CC 2015.4, MIDI2LR 0.9.9, Novation Nocturn

**Comment by rsjaffe** [comment] 2016-03-03 18:55
@boomerek So one raw version (DNG) doesn't work, but others do? Are you DNGs "special" (e.g., for HDRs made by LR only)? For the sliders that work on NEF CR2 and ORF but don't work on DNGs, is the slider range the same?

**Comment by boomerek** [comment] 2016-03-03 19:03
DNG I have aren't actually RAW files from camera. Those are converted in Lightroom TIFF and PSD files that I didn't needed in layers anymore (just to save space) 
Sliders range in those is the same as in TIFF and PSD files (temperature isn't in Kelvins but in -100 to 100 range for example)

**Comment by StevenKersting** [comment] 2016-03-03 19:17
If I change the controller program/configuration, what updates and what doesn't changes. I.e. in one configuration temp/tint do not update but exp/contr do, and it's the opposite in the other other configuration.
I still haven't found an apparent reason. Does LR reply on specific channel/encoder assignments?

**Comment by rsjaffe** [comment] 2016-03-03 19:28
Could you attach the files showing those two configurations? You'll have to zip the xml files--github doesn't accept xml directly.

**Comment by StevenKersting** [comment] 2016-03-03 21:16
If you mean the xml profile for M2LR, it's the same one. It's the controller itself that changes (channels/encoder number).

**Comment by phaul2001** [comment] 2016-03-03 21:41
Hello,

I can also report a kind of misbehaviour.
PC, TouchOSC, RAF (FujiX).
Initially the knobs update and work only after when I change them and they pick up the position of the LR fader. Onwards then they update whith the next picture (but only sometimes and sometimes only the sliders which I changed).
It seems in both options with pick up modus enabled and without.

**Comment by StevenKersting** [comment] 2016-03-03 22:21
Making progress...
I've gotten most of them updating normally. I had to assign the encoder a different function adjust it, then reassign it to the original function. After that it started working. (the xml's have been carried over for several versions now).

I still have an issue though, and I think I know why. I can change an encoder's function (channel) by pushing it's integrated switch. But doing that doesn't cause an update. And I think the midi feedback is being sent on the encoders original channel (not the new channel).

**Comment by StevenKersting** [comment] 2016-03-03 23:09
Further feedback on *my* issues... my xml and controller settings are to complex for the limited amount of communication going on. It seems the assignments/channels/communication patterns are established when the xml profile loads and is based on the visible/active encoders at that moment.

If I change the controller configuration and assign a "new" encoder to control a function that was assigned to a different encoder when the xml first loaded, it won't update (the LR returns go to the original encoder). 
Interestingly, this is true even if I assign the same channel and number to the "new encoder" so that M2LR sees it as the same command/controller. It will update if I change the function and then change it back in the xml (reloads the xml), but then the original encoder that was updating (previous controller config) quits updating if I switch back to that config.

I hope that makes sense. If not, and you want, I can make a quick video of what's going on.
Looking at the controllers that are having "these issues"... I'm guessing that similar may be going on.

**Comment by rsjaffe** [comment] 2016-03-04 00:00
OK. Does this mean you have multiple controls mapped to the same command?

Looking at the FAQ in the Wiki, one thing missing from it is the known limitation that currently, in any given "Profile" (XML file), you can map multiple buttons to a single command, but you should only map one continuous control channel (slider, fader, encoder) to a single command. For a while, we had the app enforce that limitation, but recently removed it as it was interfering with the workflow when people were remapping their devices. 

For each command, MIDI2LR only sends an update to one of the controllers mapped to that command, no matter how many controllers are mapped to it. This is buried so deep in the logic of the application (and written by my predecessor Parth), that I have not tried to address it. Anyone is welcome to dig in to the code and change that. If you do fix it, please send a pull request so I can put that into the application.

MIDI2LR identifies the each control by its control channel. If, when changing configs in your controller, you are able to reassign the control channel to the correct control, that will avoid this issue. If you have to map to different control channels, MIDI2LR handles changes in controller assignments through the "profiles" facility--which allows wholesale remapping of the controller while avoiding duplicate control channel assignments, so enacting a profile change at the same time that you remap your controller should avoid the problem.

**Comment by StevenKersting** [comment] 2016-03-04 02:52
Yes, multiple encoders to one command within a profile... but, I have also tried assigning the encoder's channel and CC to the same values in the secondary config. Logically, M2LR should see that as being the same encoder. But it does not, it doesn't update. That part doesn't make sense to me.

Additionally, if an encoder is "missing" when the profile is loaded it does not update when activated (or after). I think this is related to the lack of active monitoring of the controller (i.e. the need for the rescan midi button).

**Comment by rsjaffe** [comment] 2016-03-04 06:06
MIDI2LR only does a full refresh when profiles are changed. The program assumes that that is the only time when the MIDI controller has lost its synchronization with the app. All other times, when LR signals a change, MIDI2LR sends only the changed values, assuming the controller hasn't lost memory of the other values. Sending all the values all the time has annoying side effects for many controllers. 

I don't have one of your controllers, but it sounds like the values are not retained when the controler's configure changes. Can your controller send a change message to MIDI2LR when you change configs?  

It is very difficult for an application to continuously monitor the status of a MIDI controller. That's why the app has a rescan button. The more the controller can tell the app about its status the better the two can work together.

**Comment by StevenKersting** [comment] 2016-03-04 13:37
I can send change messages and load additional xml's... it just gets convoluted with what I'm trying to do.

Is seems Midi2LR is *not* identifying an encoder by channel and number... it seems to be using something else (unique hardware identifier?). 
Even if I assign two encoders to the same channel/number and to the same function, both will affect changes in LR, but only the first one will update (only done as a test). And if the encoders have different channels/numbers only the first will update (undocumented/known limitation).

And I found a controller limitation in it's documentation. It's not written clearly but it states: "If the encoder switch MIDI channel or number settings are changed from default the color and animation controls do NOT change." Basically, when an encoder is "switched" (a normal function) it outputs on the switch's channel/# but it's setting indication (animation state) needs to return on the encoder's original channel/#. This is not configurable in the controller, and it's not something Midi2LR could reasonably track/know. 

The only way to make this behave reasonably is in pickup mode (the controller doesn't loose track of what it did). But that kind of defeats the goal because a profile change cannot also affect a mode change. And pickup mode is rather clunky in comparison. 
You could add this as a MidiFighter Twister limitation.

**Comment by StevenKersting** [comment] 2016-03-04 14:36
Looking at the other two controllers in use with this type of issue: 
I *think* the common issue is switching controller profiles/layouts without a corresponding Midi2LR profile(xml) change. This results in multiple encoders assigned to the same function within a profile(xml).

If that was done *at any time* you may have "broken" the profile(xml), even if the controller profile/layout is reverted to original. To get it to work again you have to reassign the encoder function to something else, and then assign it back again (re-save profile). You can ignore/not access the redundancies w/in the profile, but it is probably better to remove them.

**Comment by TheRealCookie** [comment] 2016-04-04 19:26
As far I as can follow/understand your conversation, i have the same issue. No data is send to the Midi-Controller using JEPG files. Only RAW files works.
(Today I started first time with Midi2LR and thought this is normal! :D - but normaly I use RAW files, so it's not a bummer)

**Comment by rsjaffe** [comment] 2016-04-05 02:15
What controller are you using?

**Comment by TheRealCookie** [comment] 2016-04-05 07:10
X-Touch mini for now.

**Comment by joris818** [comment] 2016-04-06 06:59
I'm having some issues as well. 
Using Windows 10, Lightroom CC with Midi2lr 0.9.10.1 and Behringer BCR2000.

Strange thing is, on my laptop (same setup) everything works perfectly but on my home pc none of my knobs will update, also I can't change temp.
Worked fine before.

Using raw files !

**Comment by joris818** [comment] 2016-04-06 07:50
Also, if I request "Rescan Midi Devices", the plugin crashes.

**Comment by rsjaffe** [comment] 2016-04-06 13:55
Does the plugin crash on both computers or just the home pc? Are there any differences between the two for the following: background processes? (use ctrl-shift-esc to bring up task manager).

Something in the PC setup is causing the problem, since the program works fine in one situation and not the other. I have been unable to figure out what causes this problem since I cannot reproduce it. This might help.

**Closed** 2016-06-18 15:23 UTC
Labels: Anyone else experiencing this issue?, MIDI message handling, Troubleshooting
