### ISSUE TITLE
Mapping a sequence of shortcuts to a button

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#389] opened 2017-06-09 20:09 UTC
See user request here: https://groups.google.com/forum/#!msg/midi2lr/tNisMPIR4Vc/9PVxJok_AQAJ

**Comment by rsjaffe** [comment] 2017-10-05 00:44
Duplicate of #283

**Closed by rsjaffe** 2017-10-05 00:44 UTC
Labels: Enhancement, ready
