### ISSUE TITLE
BCF2000 slider pegged when Temp is below 3000

### ISSUE THREAD

**Issue by bigbasec** [rsjaffe/MIDI2LR#79] opened 2015-12-09 02:17 UTC
So anytime an image was shot at a temp below 2950, the slider pegs to the top.  If you bring it manually(with your mouse) any lower, the slider comes down from the top slightly.  

Seems as though there is no way to set the "range" for a given slider, so there isn't any way to fix something like this.  I would think that 2000 should be the low end, and 50,000 the high end.

**Comment by krakozavr** [comment] 2015-12-09 04:12
In LightRoom, go to Plug-in Extras ->MIDI2LR ->Set Options
Then, open the last tab "other settings"

**Comment by bigbasec** [comment] 2015-12-09 05:07
It's 2 sliders and it's impossible to change it to the actual values.  Touching the bottom limit one it goes to 150, which is well below the bottom of the scale that is usable.

**Comment by mbihn** [comment] 2015-12-09 22:48
OK, I found the problem. 
When you select a JPG the scale for temp. ist -100 to +100, but wenn you select a RAW-File, die scale chances to 2000 - 50000 (Kelvin). So in order to work fine, MIDI2LR has to Read to current status/type of the picture or the current range/value of tempature an change the behavior for each. 
For me it's fine, because I work to 99% with raw files.

**Comment by bigbasec** [comment] 2015-12-10 01:57
Right, but how to get to the 2000?  My slider won't allow me to go that low, and the other settings doesn't let me type in a value, it's just a slider, and it won't let me set it that low either.

**Comment by rsjaffe** [comment] 2015-12-10 14:29
Bug. Will fix ASAP.

**Comment by bigbasec** [comment] 2015-12-10 17:34
Thank you sir.   Guess it's about time to setup a build environment.  :)  Also notices that this was on the main page "The project files for Visual Studio and Xcode are located in Builds/", but there doesn't seem to be a Builds directory in the git repository.  Any ideas?

**Comment by mischnic** [comment] 2015-12-10 18:09
Jucer is a system for cross plattform compability. That is what the "MIDI2LR.jucer" file is for, it contains the dependencies for the programm. This file is read by "Projucer", a program to build the actual Visual Studio and Xcode projects. Then, using these, you can build the plattform-specific programm.

**Comment by rsjaffe** [comment] 2015-12-11 00:15
The app is C++ compiled and requires Jucer to produce the build environment.

The plugin is Lua and interpreted. Edits to the Lua files are recognized
the next time LR starts, so rebuilding is not needed.

Lua is sort of like a very weird sister to JavaScript, is fairly easy to
learn, but has some quite unexpected behaviors, so it's easy to go wrong
with it. For example, you'll see some places in the code where it looks
like I'm assigning a variable to itself but that's not what is happening.
Also, tables and functions are assigned by reference, so you may end up
with several different variables pointing to the same table. Altering a
value in one alters it in all.

The "develop" branch has the most recent stable code, and I suggest you
fork that if you want to contribute to the project.

**Comment by rsjaffe** [comment] 2015-12-11 04:01
Bugfix in https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.7.0a . Please test and see if this fixes problem. Note that the adjustments dialog will not work properly with jpg. This will be fixed in next release.

**Closed by rsjaffe** 2015-12-11 04:01 UTC
Labels: bug

**Comment by bigbasec** [comment] 2015-12-11 21:34
Doesn't fix the issue w/ setting the temp limits for RAW.  Highest values I can set in the GUI are 100/100.  Which would work for JPEG, but obviously don't work for RAW.   Can the value just be changed to a text box so I could enter 2000 for the low end?
