### ISSUE TITLE
Paste Selected Settings action not working correctly 0.8.0 

### ISSUE THREAD

**Issue by C0d3Rush** [rsjaffe/MIDI2LR#105] opened 2015-12-22 20:40 UTC
Hi rsjaffe,

I started using <b>MIDI2LR v0.8.0</b> today with the behringer x-touch compact (on Win 10, LR cc) and I am really impressed, thanks for an amazing plugin! However I am struggling to get the <b>Paste Selected Settings action</b> to work correctly. The Exposure up to the Clarity sliders in LR does not seem to adjust correctly after using the paste selected settings..

I have tried different selections under options and even selected them all. But the only slider(from exposure to clarity) that moves is the shadows and always just to +5 behaving as if it has been hard coded. The rest of the sliders seem to be working fine duplicating what was copied previously.

The normal "CopySettings" and "PasteSettings" works correctly.

I have followed your instructions with 
https://github.com/rsjaffe/MIDI2LR/wiki/Commands:-Tools & 
https://github.com/rsjaffe/MIDI2LR/wiki/Set-options-dialog .

Also i had to select them manually one by one... the "set all" was reset to the previous selections when I press "OK" and went back to the "Set Options >> Paste selections"...and was not saved. 
Not sure if it could be due to "Juce library updated to 4.0.2."

Any advice please? 

Thanks,
Paul

**Comment by krakozavr** [comment] 2015-12-22 20:45
I'm not sure if I understand you properly, but why you assigned this action for sliders? It's wired. I believe you have to reassign it to a buttons and check what will happened.

**Comment by C0d3Rush** [comment] 2015-12-22 20:50
Sorry I was not clear. It has been assigned to a button. The selective paste does not update the LR sliders exposure through to clarity in the basic. Although I selected them to be pasted in the options. Does that make more sense?

**Comment by C0d3Rush** [comment] 2015-12-22 20:55
So I copied and wanted to paste the following with selected paste.

Temp 4751
Tint +8

Exposure +0.83
Contrast +35

Highlights -13
Shadows +29
Whites -2
Blacks -31

Clarity +20
Vibrance +7
Saturtation -23

When I paste I get:

Temp 4751
Tint +8

Exposure 0.00
Contrast +25

Highlights 0
Shadows +5
Whites 0
Blacks 0

Clarity 0
Vibrance +7
Saturtation -23

Hope this helps.

**Comment by C0d3Rush** [comment] 2015-12-22 21:00
Sorry I was not clear. It has been assigned to a button. The selective paste does not update the LR sliders exposure through to clarity in the basic. Although I selected them to be pasted in the options. 

<b>So I copied and wanted to paste the following with selected paste.</b>

Temp 4751
Tint +8

Exposure +0.83
Contrast +35       

Highlights -13
Shadows +29      
Whites -2
Blacks -31

Clarity +20
Vibrance +7
Saturtation -23

<b>When I paste I get:</b>

Temp 4751
Tint +8

Exposure 0.00
Contrast +25       

Highlights 0
Shadows +5        
Whites 0
Blacks 0

Clarity 0
Vibrance +7
Saturtation -23

Hope this helps.

**Comment by rsjaffe** [comment] 2015-12-22 21:21
Of the following, which do you have assigned to a control on your MIDI controller?

Temp 
Tint
Exposure
Contrast
Highlights
Shadows
Whites
Blacks
Clarity
Vibrance
Saturation

**Comment by C0d3Rush** [comment] 2015-12-22 21:27
I assigned all of the above mentioned. tried only exposure to blacks selected. tried all options selected. tried different combinations but got the same result. tried to copy different photo settings but still got the same results for:  
Exposure
Contrast
Highlights
Shadows
Whites
Blacks
Clarity
Shadows are always +5 and contrast always +25.

**Comment by C0d3Rush** [comment] 2015-12-22 21:30
I have them all assigned.

**Comment by rsjaffe** [comment] 2015-12-22 21:53
Which are assigned to knobs and which to sliders?

**Comment by C0d3Rush** [comment] 2015-12-22 22:18
Temp  - knob
Tint  - knob
Exposure - slider
Contrast - slider
Highlights - slider
Shadows - slider
Whites - slider
Blacks - slider
Clarity - knob
Vibrance - knob
Saturation -  - knob

do you think LrDevelopController.setValue is not working correctly?
it resets some to 0 as if to a default??
could one not set up a copy of MIDI2LR.Copied_Settings with selected values and call 
LrApplication.activeCatalog():getTargetPhoto():applyDevelopSettings(MIDI2LR.Copied_Settings)?

I do not know LUA or C++ or how the LR API works so excuse my ignorance. But I would love to learn and help in future if possible.

**Comment by C0d3Rush** [comment] 2015-12-23 07:44
@rsjaffe - Can you duplicate the issue? Is there something I can do to help resolve it? (perhaps a debug build I can use to help?) 

The Paste Selected Settings action is important for my work flow and I would really love to help resolve it if possible. Is anyone else experiencing similar issues(win 10 LR CC)?

**Comment by rsjaffe** [comment] 2015-12-23 18:31
Can you do a screenshot of your options selections for selective paste? Also, could you send the exact sequence of steps that reproduce the event--starting with copy all settings. And are both photos of the same file type? (e.g., DNG, ARW, JPG)

For learning Lua--it's kind of similar-looking to javascript though there are some important differences in how it works.

**Comment by rsjaffe** [comment] 2015-12-23 18:51
[And here's a link to a copy of the SDK documentation.](http://lightroomsolutions.com/sdk/)

**Comment by EugeneMichel** [comment] 2015-12-24 01:04
I have the same issue. It doesn't paste my selections. Another issue I am having is not being able to save my selections in the  "Set Options > Paste Selections" Menu. I select some items and click ok, but when I go back to it, it did not save my selections and has random ones selected.

**Comment by C0d3Rush** [comment] 2015-12-25 14:15
@rsjaffe - thanks for the links. I have compiled a flow of what I did using screen shots. I use only DNG's in this case. hope this is helpful.
![midi2lr_selective_paste_issue](https://cloud.githubusercontent.com/assets/13675068/12003324/3b296fe0-ab22-11e5-9393-2ebdd7533d05.jpg)

@EugeneMichel - I have found that if I use the "clear all/ select all" and making changes it does not save. If i do it all manually only it saves the options made for "paste selective". Are you also using Win 10 with LR CC?

**Comment by rsjaffe** [comment] 2015-12-25 17:53
Those screenshots are very helpful. I'll look into repeating the problem.

For programming in Lua, http://www.lua.org/manual/5.1/ is the reference manual for version 5.1 of the language, which Lightroom currently uses. I used the current 5.2 version of the book [Programming in Lua](http://goo.gl/cajXvX) to learn how to program in the language--it goes into some of the idioms that are associated with this language.

**Comment by rsjaffe** [comment] 2015-12-25 18:21
I'm able to repeat the problem. I'll work on it and get a fix out asap.

**Comment by C0d3Rush** [comment] 2015-12-26 13:36
@rsjaffe - Awesome, thanks so much for the effort. Looking forward to the fix.
I just purchased [The C++ Programming Language, 4th Edition](http://www.amazon.com/The-Programming-Language-4th-Edition/dp/0321563840/ref=dp_ob_image_bk) by Bjarne Stroustrup and I am well impressed with the way it is written. I have been unable to obtain a good Lua book here in the book shops.
Thanks for the links!

**Comment by rsjaffe** [comment] 2015-12-28 04:46
Fixed in version [v0.8.2](https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.8.2). Read the release notes and the new information in the Options dialog. Turns out Lightroom uses undocumented variables for copy paste settings!

**Closed by rsjaffe** 2015-12-28 04:46 UTC
Labels: bug

**Comment by C0d3Rush** [comment] 2016-01-03 16:50
@rsjaffe - thanks so much for all your efforts! Really appreciate it!!
I am trying to create a build for windows now using VS. 
Happy new year to you!

**Comment by C0d3Rush** [comment] 2016-01-03 17:14
Rock on!!! works great thanks so much!
