### ISSUE TITLE
Consider auto-sync flag when applying settings

### ISSUE THREAD

**Issue by mathieucarbou** [rsjaffe/MIDI2LR#386] opened 2017-04-11 17:14 UTC
See: https://groups.google.com/forum/#!msg/midi2lr/siYOF2WL8UY/azWt0SKwCwAJ

Right, the patch that I added go through applying develop settings now and for that we have to target an image.
The problem is not new: other settings are also applied only to the target image.

The culprit is this line in client utilities I think:

LrApplication.activeCataloggetTargetPhotoapplyDevelopSettings():():(settings)

Rory: I don't know if we can check the status of the auto-sync switch. Do we ? If we can, we could add an if statement that applies to all with: catalog:getTargetPhotos().

I am also wondering if just using catalog:getTargetPhotos() would take in consideration the auto-sync switch…

**Comment by rsjaffe** [comment] 2017-04-18 15:22
No, we can't check the auto-sync switch.

**Comment by mathieucarbou** [comment] 2017-04-18 16:00
And do you know if `catalog:getTargetPhotos().` (which is different than getting the selected photos) would consider it ? Meaning that if no tenabled, the list would have 0 or 1 item and if enabled, the list would have 0..N items ?

**Comment by rsjaffe** [comment] 2018-01-05 05:06
Duplicate of #414

**Closed by rsjaffe** 2018-01-05 05:06 UTC
Labels: Enhancement, ready
