### ISSUE TITLE
Crashes on exit at M1

### ISSUE THREAD

**Issue by remov-b4-flight** [rsjaffe/MIDI2LR#499] opened 2021-01-01 03:45 UTC
**Describe the bug**
MIDI2LR sometimes crashes on exit.
Machine is Newly I got M1 MBA. Unclear with processor Intel/ARM difference.

[MIDI2LR_2021-01-01-122837_ricky.crash.txt](https://github.com/rsjaffe/MIDI2LR/files/5758617/MIDI2LR_2021-01-01-122837_ricky.crash.txt)

**To Reproduce**
1. Launch Lightroom
2. Automatically launched MIDI2LR
3. Working with LR (even no MIDI2LR touched)
4. Exit Lightroom

**Expected behavior**
Lightroom & MIDI2LR normally exit.

**System(please complete the following information):**
 - OS: Big Sur 11.1
 - Lightroom version 10.1
 - MIDI2LR version 4.2.1.0

**Comment by rsjaffe** [comment] 2021-01-01 17:34
could you replace MIDI2LR.app in the MIDI2LR.lrplugin bundle with the contents of this zip file? https://www.dropbox.com/s/7znsj06fml7u7r4/MIDI2LRdebug.zip?dl=0

This is the same version of MIDI2LR.app but includes debug symbols. Reply with a new crash dump—I hope the symbols will help me interpret it better.

**Comment by rsjaffe** [comment] 2021-01-01 21:56
Does it consistently crash on closing when you do the following?
1. start MIDI2LR normally
2. change one of the command assignments
3. close MIDI2LR without first trying to save the new profile

**Comment by rsjaffe** [comment] 2021-01-02 19:03
Try the new release 4.3.0.0 and see if that fixes things.

**Comment by remov-b4-flight** [comment] 2021-01-03 06:04
Is this crash log that you want? (debug version of 4.2.1.0)
[MIDI2LR_2021-01-02-230613_ricky.crash.txt](https://github.com/rsjaffe/MIDI2LR/files/5761264/MIDI2LR_2021-01-02-230613_ricky.crash.txt)
Crash not seem to be related save profile or not
Crash continues 4.3.0.0 also.

**Comment by rsjaffe** [comment] 2021-01-03 18:22
Could you attach a copy of the MIDI2LR.log file showing the crash? That'll help me identify when in the shutdown process it occurs. The file is found in ~/Library/Logs/MIDI2LR.

**Comment by remov-b4-flight** [comment] 2021-01-03 21:01
This is Log [MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/5762267/MIDI2LR.log)

**Comment by rsjaffe** [comment] 2021-01-03 21:58
OK, so the crash is happening very late in the shutdown process. Here's a new version of 4.3 where I've delayed destroying the main window, to see if that's the issue. Could you see if this fixes it? Inside the zip file is MIDI2LR.app. Replace the old version inside MIDI2LR.lrplugin with this to update. https://www.dropbox.com/s/v7fn21drzs8jwfx/MIDI2LR42plus.zip?dl=0

**Comment by rsjaffe** [comment] 2021-01-03 22:22
It's crashing late in shutdown. I'm going to delay zeroing out some pointers and see if that helps. Here's a new version of MIDI2LR.app. Unzip and replace the MIDI2LR.app inside MIDI2LR.lrplugin with this version to see if the problem is fixed. Thanks. https://www.dropbox.com/s/7xeos4vlfpa34cn/MIDI2LR43extra.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-04 12:56
This seems to be good.

**Comment by rsjaffe** [comment] 2021-01-04 18:39
Thanks! Could you try this final version of MIDI2LR.app? If this works, I'll make this a new bug-fix release. Thank you for you work. https://www.dropbox.com/s/1waxfi2c6hybzh5/MIDI2LR431.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-05 14:21
Oh, The new MIDI2LR.app and previous one also crashed.

**Comment by rsjaffe** [comment] 2021-01-05 18:31
One more try. If this fails, then the problem is probably with the third-party libraries I use. https://www.dropbox.com/s/vealqn4wr4u13pv/MIDI2LR431plus.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-06 20:57
Hmm... it crashes at about half the rate.

**Comment by rsjaffe** [comment] 2021-01-06 22:29
One last? try. https://www.dropbox.com/s/iaojlqz4uukf69o/MIDI2LR4313.zip?dl=0

**Comment by rsjaffe** [comment] 2021-01-08 17:01
I did find one more potential race condition. Could you try this version 4.3.1.4: https://www.dropbox.com/s/3ljyifr1ryupuft/MIDI2LR4314.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-09 09:02
Both crashes...

**Comment by rsjaffe** [comment] 2021-01-10 23:59
Unfortunately I'm having trouble interpreting the crash data. Here's yet one more try at fixing the shutdown issue. Could you try this? If it crashes, please attach the crash report again. Thanks for your work. https://www.dropbox.com/s/9fxdn1d2speq9ox/MIDI2LR4315.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-11 10:45
Here's 4.3.1.5 log
[MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/5795231/MIDI2LR.log)

[MIDI2LR_2021-01-11-193519_ricky.crash.txt](https://github.com/rsjaffe/MIDI2LR/files/5795234/MIDI2LR_2021-01-11-193519_ricky.crash.txt)

**Comment by rsjaffe** [comment] 2021-01-21 23:43
Still working on it. Could you try this 4.3.1.6? It should label the threads in the crash report. If it crashes, please post crash report again. Thanks. https://www.dropbox.com/s/yqn3ih7q59ixum2/MIDI2LR4316.zip?dl=0

**Comment by remov-b4-flight** [comment] 2021-01-30 07:37
sorry for absent. still crashed.

**Comment by rsjaffe** [comment] 2021-01-30 16:59
Thanks for testing that. Could you post the crash report?

**Comment by remov-b4-flight** [comment] 2021-01-31 07:44
4.3.1.6 logs
[MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/5899338/MIDI2LR.log)
[MIDI2LR_2021-01-31-163935_ricky.crash.txt](https://github.com/rsjaffe/MIDI2LR/files/5899339/MIDI2LR_2021-01-31-163935_ricky.crash.txt)

**Comment by rsjaffe** [comment] 2021-01-31 21:22
Now I know exactly where it crashed. There's a race condition, but it's in a 3-rd party library, so hard to trace. I believe the following fixes it. Could you try this and tell me if things are now ok? https://www.dropbox.com/s/m8imasnr0anv2b0/MIDI2LR4317.zip?dl=0

**Comment by rsjaffe** [comment] 2021-02-06 00:39
Were you able to test the latest patch?

**Comment by remov-b4-flight** [comment] 2021-02-07 12:51
Still crashing...
[MIDI2LR_2021-02-07-213908_ricky.crash.txt](https://github.com/rsjaffe/MIDI2LR/files/5938994/MIDI2LR_2021-02-07-213908_ricky.crash.txt)
[MIDI2LR.log](https://github.com/rsjaffe/MIDI2LR/files/5938995/MIDI2LR.log)

**Comment by rsjaffe** [comment] 2021-02-09 00:15
Thanks. Here's another attempt to fix the race condition to test: https://www.dropbox.com/s/ztix0vqywsp87dx/MIDI2LR4318.zip?dl=0

**Comment by rsjaffe** [comment] 2021-02-09 17:11
Here's version 4.3.1.9. Please reply with results and mention version #. Thanks. In this version I changed the threading model for shutdown. 
https://www.dropbox.com/s/oywl8rura1a5xb8/MIDI2LR4319.zip?dl=0

**Comment by rsjaffe** [comment] 2021-02-10 21:28
This link is to version 4.3.1.10 : if you could test it and reply with results and version number I'd appreciate it: https://www.dropbox.com/s/ehkecw2knyxw74a/MIDI2LR43110.zip?dl=0

**Comment by rsjaffe** [comment] 2021-11-14 02:03
Fixed in 5.1.1

**Closed by rsjaffe** 2021-11-14 02:03 UTC
Labels: Bug
